### get all
GET localhost:8484/findAll?service=unbong

### 注册服务
POST localhost:8484/reg?service=unbong
Content-Type: application/json

{
  "context": "http",
  "host": "127.0.0.1",
  "port": "8803",
  "schema": "http",
  "status": false,

  "parameters": {"env": "dev"}
}

### 取消注册
POST localhost:8484/unreg?service=unbong
Content-Type: application/json

{
  "context": "http",
  "host": "127.0.0.1",
  "port": "8801",
  "schema": "http",
  "status": false,

  "parameters": {"env": "dev"}
}



### get cluster
GET localhost:8484/cluster


### get info
GET localhost:8484/info


### get leader
GET localhost:8484/leader

### set leader
GET localhost:8485/sl

### get snap shot
GET localhost:8485/snapshot

